(add-to-list 'load-path (concat dotfiles-dir "plugins/grails"))
(add-to-list 'load-path (concat dotfiles-dir "./"))
;(require 'jacobo/project-mode-customization)
(load (concat dotfiles-dir "jacobo/project-mode-custumization.el"))
(require 'grails-mode)
(setq grails-mode t)
(setq project-mode t)
(add-to-list 'auto-mode-alist '("\.gsp$" . nxml-mode))
(provide 'jacobo/grails)
